.PHONY: clean All

All:
	@echo "----------Building project:[ TaskG - Release ]----------"
	@cd "TaskG" && "$(MAKE)" -f  "TaskG.mk"
clean:
	@echo "----------Cleaning project:[ TaskG - Release ]----------"
	@cd "TaskG" && "$(MAKE)" -f  "TaskG.mk" clean
